<?php $cookieName = "site-notification-2024-05-11"; ?>
<?php $giveAnnouncement = false; // disabled - inherited p2sr announcement removed, set true + edit text below for your own ?>

<?php if (!isset($_COOKIE[$cookieName]) && $giveAnnouncement): ?>

    <div id="announcement">
        <span class="notification">
            <b>Announcement:</b> Welcome to Propulsion Hub! Check out the <a href="/forum" target="_blank"><b>forum</b></a> for updates.
        </span>
        <span class="close-btn"></span>
    </div>

    <script>
        $(document).ready(function() {
            setTimeout(function() {
                $("#announcement").slideDown("slow");
            }, 2000);

            $("#announcement .close-btn").click(function() {
                $("#announcement").slideUp("slow");
                var d = new Date();
                d.setTime(d.getTime() + (10 * 365 * 24 * 60 * 60 * 1000)); //10 years
                var expires = "expires="+d.toGMTString();
                document.cookie = "<?=$cookieName?>=yes; path=/; " + expires;
            });
        });
    </script>

<?php endif; ?>