<div id="footer">
    <div class="footerleft">
        Personal fork maintained by Unkn0wngb. Original Portal2Boards codebase by <a href="/profile/76561198043770492" target="_blank">ncla</a>, <a href="/profile/76561198047900528" target="_blank">iVerb</a>, and the p2sr community.
    </div>
    <div class="footeright"><span style="margin-right: 25px">This page was generated in <?php echo round(microtime(true) - $this->startupTimestamp, 3); ?> seconds</span><a href="javascript:toggleTheme()">Toggle Light/Dark Mode</a></div>
</div>
